### PR TITLE
Bugfix: correctly get projects in solution folders

### PR DESCRIPTION
**Pull request by wangzq**
Hello, thank you for your contribution! Can you please provide a quick example of what this pull request accomplishes or fixes, versus what the plugin does now? That way I can verify it's all working correctly and accept your request. thank you!

### CODE REVIEW

**Comment by mistoll** [comment]
Please merge this. 
In some solutions the current implementation does not generate a graph (blank output). This is fixed by this PR.

**Comment by wangzq** [comment]
Looks like I missed the first comment, yes this PR is used to handle solutions with projects in solution folders. You should be able to repro and verify this by just moving any projects into solution folders.

**Comment by brentkrueger** [comment]
Hi wangzq,

I was able to reproduce the issue, by adding a project directly into the solution folder like you mentioned. However, the PR didn't seem to resolve this, unless I'm missing something? I patched with your PR locally, and debugged to ensure that your new DTE class was being used etc, still seeing the sequence contains more than one element exception. Could you send me a message at vs2015packagevisualizer@kruegerwebdesign.com and we can work together on this? thanks

**Comment by mistoll** [comment]
AFAIK, the "sequence contains more than one element" issue (#4) is NOT related to this PR.

This PR handles the location of the projects within a solution.
#4 is triggered by different versions of installed nuget packages in the projects of a solution.

The latter does not change with this PR.

**Pull request merged**
